#!/usr/bin/env python3
"""Sync Codex SKILL.md directories into other AI coding tool formats."""

from __future__ import annotations

import argparse
import dataclasses
import hashlib
import os
import re
import shutil
import sys
from pathlib import Path
from typing import Callable, Iterable


MARKER = "Generated by skill-sync"
META_FILE = ".skill-sync-meta"
SUPPORTED_TARGETS = ("cursor", "codex", "trae", "claude", "windsurf", "copilot")


@dataclasses.dataclass(frozen=True)
class Skill:
    name: str
    path: Path
    skill_md: Path
    content: str
    frontmatter: dict[str, str]
    body: str

    @property
    def description(self) -> str:
        return self.frontmatter.get("description", "").strip()


@dataclasses.dataclass(frozen=True)
class WritePlan:
    target: str
    skill: str
    path: Path
    content: str | None = None
    copy_from: Path | None = None


def main() -> int:
    parser = argparse.ArgumentParser(description="Sync Codex skills into other coding tool formats.")
    parser.add_argument("source", nargs="?", default=".", help="Skill directory or root containing skill directories.")
    parser.add_argument(
        "--targets",
        default="cursor,codex,trae",
        help=f"Comma-separated targets. Supported: {', '.join(SUPPORTED_TARGETS)}.",
    )
    parser.add_argument("--project", default=".", help="Project root for project-scoped targets.")
    parser.add_argument("--dry-run", action="store_true", help="Preview changes without writing files.")
    parser.add_argument("--remove-stale", action="store_true", help="Remove generated files for missing source skills.")
    parser.add_argument(
        "--target-root",
        action="append",
        default=[],
        metavar="TARGET=PATH",
        help="Override a target output directory. Can be passed more than once.",
    )
    args = parser.parse_args()

    source = Path(args.source).expanduser().resolve()
    project = Path(args.project).expanduser().resolve()
    targets = parse_targets(args.targets)
    overrides = parse_target_roots(args.target_root)

    skills = discover_skills(source)
    if not skills:
        print(f"No skills found under {source}", file=sys.stderr)
        return 1

    plans: list[WritePlan] = []
    for target in targets:
        root = target_root(target, project, overrides)
        renderer = renderer_for(target)
        for skill in skills:
            plans.append(renderer(skill, root))

    apply_plans(plans, dry_run=args.dry_run)
    if args.remove_stale:
        remove_stale(targets, skills, project, overrides, dry_run=args.dry_run)

    return 0


def parse_targets(value: str) -> list[str]:
    targets = [item.strip().lower() for item in value.split(",") if item.strip()]
    unknown = sorted(set(targets) - set(SUPPORTED_TARGETS))
    if unknown:
        raise SystemExit(f"Unsupported target(s): {', '.join(unknown)}")
    return targets


def parse_target_roots(values: Iterable[str]) -> dict[str, Path]:
    roots: dict[str, Path] = {}
    for value in values:
        if "=" not in value:
            raise SystemExit(f"Invalid --target-root value: {value}")
        target, raw_path = value.split("=", 1)
        target = target.strip().lower()
        if target not in SUPPORTED_TARGETS:
            raise SystemExit(f"Unsupported --target-root target: {target}")
        roots[target] = Path(raw_path).expanduser().resolve()
    return roots


def discover_skills(source: Path) -> list[Skill]:
    if (source / "SKILL.md").is_file():
        return [load_skill(source)]

    skills: list[Skill] = []
    for child in sorted(source.iterdir()):
        if child.name.startswith(".") or not child.is_dir():
            continue
        if (child / "SKILL.md").is_file():
            skills.append(load_skill(child))
    return skills


def load_skill(path: Path) -> Skill:
    skill_md = path / "SKILL.md"
    content = skill_md.read_text(encoding="utf-8")
    frontmatter, body = split_frontmatter(content)
    name = slugify(frontmatter.get("name") or path.name)
    return Skill(name=name, path=path, skill_md=skill_md, content=content, frontmatter=frontmatter, body=body)


def split_frontmatter(content: str) -> tuple[dict[str, str], str]:
    if not content.startswith("---\n"):
        return {}, content

    end = content.find("\n---\n", 4)
    if end == -1:
        return {}, content

    raw = content[4:end].strip()
    body = content[end + len("\n---\n") :]
    result: dict[str, str] = {}
    for line in raw.splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        result[key.strip()] = value.strip().strip('"').strip("'")
    return result, body


def slugify(value: str) -> str:
    value = value.lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    value = re.sub(r"-+", "-", value).strip("-")
    return value or "skill"


def target_root(target: str, project: Path, overrides: dict[str, Path]) -> Path:
    if target in overrides:
        return overrides[target]
    if target == "codex":
        return Path(os.environ.get("CODEX_HOME", "~/.codex")).expanduser().resolve() / "skills"
    if target == "cursor":
        return project / ".cursor" / "rules"
    if target == "trae":
        return project / ".trae" / "skills"
    if target == "claude":
        return project / ".claude" / "skills"
    if target == "windsurf":
        return project / ".windsurf" / "rules"
    if target == "copilot":
        return project / ".github" / "instructions"
    raise SystemExit(f"Unsupported target: {target}")


def renderer_for(target: str) -> Callable[[Skill, Path], WritePlan]:
    renderers: dict[str, Callable[[Skill, Path], WritePlan]] = {
        "cursor": render_cursor,
        "codex": render_codex,
        "trae": render_trae,
        "claude": render_claude,
        "windsurf": render_windsurf,
        "copilot": render_copilot,
    }
    return renderers[target]


def render_cursor(skill: Skill, root: Path) -> WritePlan:
    description = skill.description or f"Use the {skill.name} skill."
    content = "\n".join(
        [
            "---",
            f"description: {quote_frontmatter(description)}",
            "alwaysApply: false",
            "---",
            "",
            f"<!-- {MARKER}; source={skill.path} -->",
            "",
            skill.body.strip(),
            "",
        ]
    )
    return WritePlan(target="cursor", skill=skill.name, path=root / f"{skill.name}.mdc", content=content)


def render_codex(skill: Skill, root: Path) -> WritePlan:
    return WritePlan(target="codex", skill=skill.name, path=root / skill.name, copy_from=skill.path)


def render_trae(skill: Skill, root: Path) -> WritePlan:
    content = rendered_markdown(skill, "Trae Skill")
    return WritePlan(target="trae", skill=skill.name, path=root / f"{skill.name}.md", content=content)


def render_claude(skill: Skill, root: Path) -> WritePlan:
    content = rendered_markdown(skill, "Claude Skill")
    return WritePlan(target="claude", skill=skill.name, path=root / f"{skill.name}.md", content=content)


def render_windsurf(skill: Skill, root: Path) -> WritePlan:
    content = rendered_markdown(skill, "Windsurf Rule")
    return WritePlan(target="windsurf", skill=skill.name, path=root / f"{skill.name}.md", content=content)


def render_copilot(skill: Skill, root: Path) -> WritePlan:
    content = rendered_markdown(skill, "GitHub Copilot Instruction")
    return WritePlan(target="copilot", skill=skill.name, path=root / f"{skill.name}.instructions.md", content=content)


def rendered_markdown(skill: Skill, title: str) -> str:
    lines = [
        f"<!-- {MARKER}; source={skill.path} -->",
        f"# {title}: {skill.name}",
        "",
    ]
    if skill.description:
        lines.extend([skill.description, ""])
    lines.extend([skill.body.strip(), ""])
    return "\n".join(lines)


def quote_frontmatter(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def apply_plans(plans: Iterable[WritePlan], dry_run: bool) -> None:
    for plan in plans:
        if plan.copy_from is not None:
            sync_directory(plan, dry_run)
        elif plan.content is not None:
            sync_file(plan, dry_run)


def sync_directory(plan: WritePlan, dry_run: bool) -> None:
    action = "create"
    if plan.path.exists():
        action = "update" if directory_digest(plan.copy_from) != directory_digest(plan.path) else "skip"
    print(f"{action:>6} {plan.target}:{plan.skill} -> {plan.path}")
    if dry_run or action == "skip":
        return
    plan.path.parent.mkdir(parents=True, exist_ok=True)
    if plan.path.exists():
        shutil.rmtree(plan.path)
    ignore = shutil.ignore_patterns(".git", "__pycache__", ".DS_Store")
    shutil.copytree(plan.copy_from, plan.path, ignore=ignore)
    (plan.path / META_FILE).write_text(f"{MARKER}\nsource={plan.copy_from}\n", encoding="utf-8")


def sync_file(plan: WritePlan, dry_run: bool) -> None:
    current = plan.path.read_text(encoding="utf-8") if plan.path.exists() else None
    action = "skip" if current == plan.content else "update" if current is not None else "create"
    print(f"{action:>6} {plan.target}:{plan.skill} -> {plan.path}")
    if dry_run or action == "skip":
        return
    plan.path.parent.mkdir(parents=True, exist_ok=True)
    plan.path.write_text(plan.content, encoding="utf-8")


def remove_stale(targets: list[str], skills: list[Skill], project: Path, overrides: dict[str, Path], dry_run: bool) -> None:
    names = {skill.name for skill in skills}
    for target in targets:
        root = target_root(target, project, overrides)
        if not root.exists():
            continue
        if target == "codex":
            remove_stale_codex(root, names, dry_run)
        else:
            remove_stale_files(root, names, dry_run)


def remove_stale_files(root: Path, names: set[str], dry_run: bool) -> None:
    for file_path in root.iterdir():
        if not file_path.is_file() or file_path.stem in names:
            continue
        try:
            content = file_path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        if MARKER not in content:
            continue
        print(f"remove stale -> {file_path}")
        if not dry_run:
            file_path.unlink()


def remove_stale_codex(root: Path, names: set[str], dry_run: bool) -> None:
    for child in root.iterdir():
        if not child.is_dir() or child.name in names:
            continue
        skill_md = child / "SKILL.md"
        meta_file = child / META_FILE
        if not skill_md.exists() or not meta_file.exists():
            continue
        print(f"remove stale -> {child}")
        if not dry_run:
            shutil.rmtree(child)


def directory_digest(path: Path | None) -> str:
    if path is None or not path.exists():
        return ""
    digest = hashlib.sha256()
    for file_path in sorted(item for item in path.rglob("*") if item.is_file()):
        if any(part in {".git", "__pycache__"} for part in file_path.parts):
            continue
        if file_path.name == META_FILE:
            continue
        relative = file_path.relative_to(path)
        digest.update(str(relative).encode("utf-8"))
        digest.update(file_path.read_bytes())
    return digest.hexdigest()


if __name__ == "__main__":
    raise SystemExit(main())
